import { bibliographySetup } from "./bib";
import { fontSize, mm, prefixed, pt, trim, TEX_LEADING_RATIO } from "./format";
import {
  FONTSPEC_SETTER,
  isSubstitution,
  mapFont,
  type FontMapping,
  type LatexFamily,
} from "./fonts";
import { listPreamble } from "./list";
import { tableNeedsOf, tablePreamble, type TableNeeds } from "./table";
import {
  DEFAULT_OPTIONS,
  usesFontspec,
  type Engine,
  type GenerationOptions,
} from "./options";
import { paragraphsOf, type Block, type Paragraph } from "@/lib/extract/body";
import { assetPathFor, type Assets } from "@/lib/extract/media";
import type {
  Alignment,
  EffectiveStyle,
  HeadingStyle,
  LineSpacing,
  NamedStyle,
  StyleProfile,
} from "@/lib/extract/types";

export const CLASS_NAME = "doctotex";

/**
 * ECMA-376 gives `w:sz` a default of 20 half-points, so a document that never
 * declares a size is asking for 10pt rather than leaving it open.
 */
const DEFAULT_BODY_SIZE_PT = 10;

/** LaTeX's own default; set explicitly so fancyhdr stops warning about it. */
const HEAD_HEIGHT_MM = 4.94;

/** geometry rejects a zero separation, and Word can legitimately ask for one. */
const MIN_SEPARATION_MM = 0.1;

/** Word outline levels, in order, to the sectioning commands they become. */
const SECTIONING = [
  "section",
  "subsection",
  "subsubsection",
  "paragraph",
  "subparagraph",
] as const;

/** Shared with the single-file layout, which has no class to carry it. */
export const BANNER: readonly string[] = [
  "%% Generated by DocToTex from the styles of a Word document.",
  "%% Every value below was read from the document; nothing is invented.",
];

export interface HeaderFooterText {
  readonly header?: string;
  readonly footer?: string;
}

/** How many paragraphs use each style, so unused ones can be labelled. */
export type StyleUsage = ReadonlyMap<string, number>;

export interface ClassInput {
  readonly profile: StyleProfile;
  /**
   * What the document says, not only how it declares itself. A face used by a
   * hand-formatted run appears nowhere in the stylesheet, and a class that
   * loaded only the declared faces would render that run in the wrong one.
   */
  readonly blocks?: readonly Block[];
  /** The pictures that travel with the sources; an absent one is not loaded for. */
  readonly assets?: Assets;
  readonly headerFooter?: HeaderFooterText;
  readonly usage?: StyleUsage;
  readonly options?: GenerationOptions;
}

/**
 * Packages the class loads only because the document uses what they provide.
 *
 * A preamble that loads everything compiles the same and reads as though the
 * document needed it, which is the opposite of what the comments are for.
 */
interface Needs {
  readonly pictures: boolean;
  readonly strikeOrUnderline: boolean;
  readonly justifiedParagraphs: boolean;
  readonly shapedParagraphs: boolean;
  readonly lists: boolean;
  readonly tables: TableNeeds;
}

function needsOf(
  profile: StyleProfile,
  blocks: readonly Block[],
  assets: Assets,
): Needs {
  const bodyAlignment = profile.defaults.paragraph.alignment ?? "left";
  const paragraphs = paragraphsOf(blocks);

  return {
    // What the document places, narrowed to what actually travels with it: a
    // picture the package did not hold is not a reason to load graphicx.
    pictures: paragraphs.some((paragraph) =>
      paragraph.runs.some(
        (run) =>
          run.kind === "image" && assets.has(assetPathFor(run.image.part)),
      ),
    ),
    strikeOrUnderline: paragraphs.some((paragraph) =>
      paragraph.runs.some(
        (run) =>
          run.kind === "text" && (run.style.underline || run.style.strike),
      ),
    ),
    // Only worth a package where the document mixes the two: a wholly
    // justified document gets justification from LaTeX for nothing.
    justifiedParagraphs:
      bodyAlignment !== "justify" &&
      paragraphs.some((p) => p.style.alignment === "justify"),
    shapedParagraphs: paragraphs.some((p) => isShaped(p, profile)),
    // Driven by what the paragraphs resolved to, not by the presence of
    // numbering.xml: Word ships that part in documents that have no list.
    lists: paragraphs.some((p) => p.list !== undefined),
    tables: tableNeedsOf(blocks),
  };
}

/**
 * Whether a paragraph asks for anything the document-wide settings do not
 * already give it. One that does not is written as plain text, which keeps the
 * generated document readable and its diffs small.
 */
export function isShaped(paragraph: Paragraph, profile: StyleProfile): boolean {
  const body = profile.defaults.paragraph;
  const own = paragraph.style;

  return (
    (own.spaceBeforePt ?? 0) !== (body.spaceBeforePt ?? 0) ||
    (own.spaceAfterPt ?? 0) !== (body.spaceAfterPt ?? 0) ||
    (own.indentLeftMm ?? 0) !== (body.indentLeftMm ?? 0) ||
    (own.indentFirstLineMm ?? 0) !== (body.indentFirstLineMm ?? 0) ||
    (own.alignment ?? "left") !== (body.alignment ?? "left")
  );
}

export function generateClass(input: ClassInput): string {
  return [
    ...BANNER,
    "\\NeedsTeXFormat{LaTeX2e}",
    `\\ProvidesClass{${CLASS_NAME}}[2026/08/14 DocToTex generated class]`,
    "",
    "\\LoadClassWithOptions{article}",
    "",
    ...preambleLines(input),
    "",
    "\\endinput",
  ].join("\n");
}

/**
 * Everything the class does apart from declaring itself a class.
 *
 * The single-file layout drops the class and pastes these into the document's
 * own preamble, so the two outputs are the same LaTeX in different wrappers
 * rather than two generators that have to be kept in agreement.
 */
export function preambleLines(input: ClassInput): readonly string[] {
  const { profile } = input;
  const options = input.options ?? DEFAULT_OPTIONS;
  const blocks = input.blocks ?? [];
  const paragraphs = paragraphsOf(blocks);
  const needs = needsOf(profile, blocks, input.assets ?? new Map());

  const bodySizePt = profile.defaults.text.fontSizePt ?? DEFAULT_BODY_SIZE_PT;
  const bodyFamily = mapFont(profile.defaults.text.fontFamily).family;
  const bibliography = bibliographySetup(options.bibliography);

  return [
    ...fontSetup(profile, paragraphs, bodySizePt, options.engine),
    ...prefixed(inlineDecorations(needs)),
    ...prefixed(pictures(needs)),
    ...prefixed(needs.lists ? listPreamble() : []),
    ...prefixed(tablePreamble(needs.tables)),
    "",
    ...geometry(profile),
    "",
    ...spacing(profile, bodySizePt, needs),
    ...prefixed(paragraphEnvironment(needs)),
    "",
    ...headings(profile, bodySizePt, bodyFamily, input.usage ?? new Map()),
    "",
    ...titleCommand(profile.title, bodySizePt, bodyFamily),
    "",
    ...pageStyle(input.headerFooter ?? {}),
    ...prefixed(bibliography.preamble),
  ];
}

/**
 * `graphicx` is what `\includegraphics` comes from. The picture's size is
 * written at each use rather than set here: Word sizes each one individually,
 * and a class-wide default would be a number no picture in the document asked
 * for.
 */
function pictures(needs: Needs): readonly string[] {
  if (!needs.pictures) {
    return [];
  }
  return ["%% The document places pictures.", "\\RequirePackage{graphicx}"];
}

/**
 * `\underline` cannot break across lines and `ulem` has no plain-LaTeX
 * equivalent, so the package is loaded — but `normalem` is not optional:
 * without it `ulem` redefines `\emph` to underline, and every italic in the
 * document would come out underlined instead.
 */
function inlineDecorations(needs: Needs): readonly string[] {
  if (!needs.strikeOrUnderline) {
    return [];
  }
  return [
    "%% The document underlines or strikes text through.",
    "\\RequirePackage[normalem]{ulem}",
  ];
}

/**
 * Every distinct typeface the document uses, so a heading in Arial over a body
 * in Times still reaches the reader in Arial. Loading only the body font would
 * silently render every style in it.
 */
function fontPlan(
  profile: StyleProfile,
  paragraphs: readonly Paragraph[],
): ReadonlyMap<string, FontMapping> {
  const families = [
    profile.defaults.text.fontFamily,
    ...profile.headings.map((heading) => heading.text.fontFamily),
    profile.title?.text.fontFamily,
    ...paragraphs.flatMap((paragraph) =>
      paragraph.runs.flatMap((run) =>
        run.kind === "text" ? [run.style.fontFamily] : [],
      ),
    ),
  ];

  const plan = new Map<string, FontMapping>();
  for (const family of families) {
    const key = family ?? "";
    if (!plan.has(key)) {
      plan.set(key, mapFont(family));
    }
  }
  return plan;
}

function fontSetup(
  profile: StyleProfile,
  paragraphs: readonly Paragraph[],
  bodySizePt: number,
  engine: Engine,
): readonly string[] {
  const plan = fontPlan(profile, paragraphs);
  const bodyFamily = mapFont(profile.defaults.text.fontFamily).family;

  const lines = usesFontspec(engine)
    ? [...fontspecSetup(plan)]
    : [...packageSetup(plan)];

  lines.push(...collisionNotes(plan));

  if (bodyFamily !== "rm") {
    lines.push(`\\renewcommand{\\familydefault}{\\${bodyFamily}default}`);
  }

  if (profile.defaults.text.fontSizePt === undefined) {
    lines.push(
      `%% The document declares no body size, so the schema default of ${DEFAULT_BODY_SIZE_PT}pt applies.`,
    );
  }
  lines.push(
    "\\renewcommand{\\normalsize}{" + fontSize(bodySizePt) + "}",
    "\\normalsize",
  );

  return lines;
}

/** pdfLaTeX: one package per face, chosen for metric compatibility. */
function packageSetup(
  plan: ReadonlyMap<string, FontMapping>,
): readonly string[] {
  const lines = [
    "%% Fonts. T1 encoding is required for accented characters to hyphenate.",
    "\\RequirePackage[T1]{fontenc}",
  ];

  const loaded = new Set<string>();
  for (const [family, mapping] of plan) {
    if (mapping.unmatched) {
      lines.push(
        `%% TODO: the document asks for "${mapping.unmatched}", which has no free`,
        "%% counterpart for pdfLaTeX. Latin Modern is substituted. Compiling with",
        "%% XeLaTeX or LuaLaTeX would load the real face through fontspec.",
      );
    }
    for (const name of mapping.packages) {
      if (!loaded.has(name)) {
        loaded.add(name);
        lines.push(`\\RequirePackage{${name}}  % ${family || "default"}`);
      }
    }
  }

  return lines;
}

/**
 * XeLaTeX and LuaLaTeX: one setter per family slot, naming a face TeX Live
 * carries. Pointing fontspec at the Word name instead would be more faithful
 * and would fail on every machine without Microsoft's fonts installed, so the
 * clone is used and the original is named in a comment beside it.
 */
function fontspecSetup(
  plan: ReadonlyMap<string, FontMapping>,
): readonly string[] {
  const lines = [
    "%% Fonts. XeLaTeX and LuaLaTeX select faces by name, through fontspec.",
    "\\RequirePackage{fontspec}",
  ];

  const filled = new Set<LatexFamily>();
  for (const [family, mapping] of plan) {
    if (filled.has(mapping.family)) {
      continue;
    }
    filled.add(mapping.family);

    const setter = FONTSPEC_SETTER[mapping.family];
    if (mapping.unmatched) {
      lines.push(
        `%% TODO: the document asks for "${mapping.unmatched}", which TeX Live does`,
        "%% not carry. Latin Modern is substituted; where the real face is installed,",
        `%% \\${setter}{${mapping.unmatched}} loads it directly.`,
      );
    } else if (isSubstitution(family, mapping)) {
      lines.push(
        `%% "${family}" is not redistributable; ${mapping.fontspec} is its metric clone.`,
      );
    }
    lines.push(`\\${setter}{${mapping.fontspec}}`);
  }

  return lines;
}

/**
 * Two different Word faces can land in the same slot — Times and Garamond are
 * both serif. Neither engine can then tell them apart, and saying so beats
 * letting one quietly become the other.
 */
function collisionNotes(
  plan: ReadonlyMap<string, FontMapping>,
): readonly string[] {
  const bySlot = new Map<LatexFamily, string[]>();
  for (const [family, mapping] of plan) {
    if (family !== "") {
      bySlot.set(mapping.family, [
        ...(bySlot.get(mapping.family) ?? []),
        family,
      ]);
    }
  }

  return [...bySlot]
    .filter(([, families]) => families.length > 1)
    .map(
      ([slot, families]) =>
        `%% TODO: ${families.join(" and ")} both map to \\${slot}family, so they render alike.`,
    );
}

function geometry(profile: StyleProfile): readonly string[] {
  const { widthMm, heightMm, margins } = profile.page;

  // Word measures the header from the page edge; geometry measures it from the
  // text block. The conversion is the top margin less the header offset and the
  // height of the header itself.
  const headSep = separation(margins.topMm - margins.headerMm - HEAD_HEIGHT_MM);
  const footSkip = separation(margins.bottomMm - margins.footerMm);

  return [
    "%% Page geometry, taken from the document's section properties.",
    "\\RequirePackage{geometry}",
    "\\geometry{",
    `  paperwidth=${mm(widthMm)},`,
    `  paperheight=${mm(heightMm)},`,
    `  top=${mm(margins.topMm)},`,
    `  bottom=${mm(margins.bottomMm)},`,
    `  left=${mm(margins.leftMm)},`,
    `  right=${mm(margins.rightMm)},`,
    `  headheight=${mm(HEAD_HEIGHT_MM)},`,
    `  headsep=${mm(headSep)},`,
    `  footskip=${mm(footSkip)}`,
    "}",
  ];
}

function spacing(
  profile: StyleProfile,
  bodySizePt: number,
  needs: Needs,
): readonly string[] {
  // `\cellcolor` comes from xcolor's table option, and an option cannot be
  // added to a package that is already loaded, so the decision is made here
  // rather than beside the tables that need it.
  const xcolor = needs.tables.cellColours
    ? "\\RequirePackage[table]{xcolor}  % table: the document shades table cells"
    : "\\RequirePackage{xcolor}";
  const lines = ["\\RequirePackage{setspace}", xcolor];

  if (needs.justifiedParagraphs) {
    lines.push(
      "%% Some paragraphs justify while the document does not, so both shapes",
      "%% have to be available rather than one being the absence of the other.",
      "\\RequirePackage{ragged2e}",
    );
  }

  lines.push(
    ...lineSpacing(profile.defaults.paragraph.lineSpacing, bodySizePt),
    ...bodyAlignment(profile.defaults.paragraph.alignment),
  );

  const { spaceBeforePt, spaceAfterPt, indentFirstLineMm } =
    profile.defaults.paragraph;

  // Both are set unconditionally. Word's defaults for an undeclared indent and
  // an undeclared paragraph spacing are zero, while LaTeX's are a 15pt indent
  // and a springy parskip — leaving them alone would indent every paragraph of
  // a document that asked for none.
  //
  // Word puts the space after one paragraph and the space before the next
  // between them and adds the two; LaTeX has the one \parskip for that gap.
  lines.push(
    `\\setlength{\\parskip}{${pt((spaceBeforePt ?? 0) + (spaceAfterPt ?? 0))}}`,
    `\\setlength{\\parindent}{${mm(indentFirstLineMm ?? 0)}}`,
  );

  return lines;
}

/**
 * `w:lineRule` says what `w:line` measures, and setspace expresses all three
 * as a factor of TeX's own leading. Reporting only the `auto` case, as this
 * used to, dropped an exactly-specified leading without saying so.
 */
function lineSpacing(
  spacing: LineSpacing | undefined,
  bodySizePt: number,
): readonly string[] {
  if (!spacing) {
    return [];
  }

  // TeX sets its baselines 1.2 times the type size apart, which is the figure
  // an absolute request has to be expressed against.
  const natural = bodySizePt * TEX_LEADING_RATIO;

  switch (spacing.kind) {
    case "multiple":
      return [`\\setstretch{${trim(spacing.value)}}`];
    case "exact":
      return [
        `%% The document asks for exactly ${trim(spacing.pt)}pt between baselines,`,
        `%% which is ${trim(spacing.pt / natural)} times TeX's own ${trim(natural)}pt.`,
        `\\setstretch{${trim(spacing.pt / natural)}}`,
      ];
    case "atLeast":
      // Below TeX's own leading the request is already met, so the floor never
      // tightens the page — it only ever opens it up.
      return [
        `%% The document asks for at least ${trim(spacing.pt)}pt between baselines;`,
        `%% TeX's own ${trim(natural)}pt already meets that where the factor would be under 1.`,
        `\\setstretch{${trim(Math.max(1, spacing.pt / natural))}}`,
      ];
  }
}

/**
 * The shape every paragraph starts in.
 *
 * ECMA-376 gives `w:jc` a default of `start`, so a document that never mentions
 * alignment is asking for ragged right — where LaTeX, left alone, justifies.
 * That difference is also most of why generated pages overflowed the margin:
 * justification stretches a line it cannot hyphenate, and ragged right does not.
 */
function bodyAlignment(alignment: Alignment | undefined): readonly string[] {
  if (alignment === undefined) {
    return [
      "%% The document declares no alignment, so the schema default of",
      '%% "start" applies, which is ragged right rather than justified.',
      "\\raggedright",
    ];
  }

  switch (alignment) {
    case "left":
      return ["\\raggedright"];
    case "right":
      return ["\\raggedleft"];
    case "center":
      return ["\\centering"];
    case "justify":
      // LaTeX's own shape; saying so beats a line that changes nothing.
      return ["%% The document justifies, which is what LaTeX already does."];
  }
}

/**
 * One paragraph that asks for spacing, indentation or alignment the document
 * as a whole does not. The arguments are always written in the same order so
 * the generated document can be read down a column.
 */
function paragraphEnvironment(needs: Needs): readonly string[] {
  if (!needs.shapedParagraphs) {
    return [];
  }

  return [
    "%% A paragraph whose own w:pPr differs from the document's defaults.",
    "%% #1 space before, #2 space after, #3 left indent, #4 first-line indent,",
    "%% #5 the alignment switch, empty where it matches the document's.",
    "%%",
    "%% The closing half of an environment cannot see its arguments, so the",
    "%% space that follows the paragraph is held in a length until it is due.",
    "%% \\begin already opens a group, which is what confines the rest.",
    "\\newlength{\\doctotexafter}",
    "\\newenvironment{doctotexpara}[5]{%",
    "  \\par\\vspace{#1}%",
    "  \\setlength{\\doctotexafter}{#2}%",
    "  \\setlength{\\leftskip}{#3}%",
    "  \\setlength{\\parindent}{#4}%",
    "  #5%",
    "}{%",
    "  \\par\\vspace{\\doctotexafter}%",
    "}",
  ];
}

function headings(
  profile: StyleProfile,
  bodySizePt: number,
  bodyFamily: LatexFamily,
  usage: StyleUsage,
): readonly string[] {
  const lines = [
    "%% Heading styles, one per outline level the document declares.",
    "\\RequirePackage{titlesec}",
  ];

  if (profile.headings.length === 0) {
    lines.push("%% The document declares no heading styles.");
    return lines;
  }

  const used = profile.headings.filter((h) => (usage.get(h.styleId) ?? 0) > 0);
  if (used.length === 0) {
    lines.push(
      "%% None of these styles is applied to any paragraph in the document:",
      "%% every heading in it is a normal paragraph formatted by hand. The",
      "%% definitions are kept so the structure can be applied by hand here.",
    );
  }

  for (const heading of profile.headings) {
    const command = SECTIONING[heading.level - 1];
    if (!command) {
      lines.push(
        `%% TODO: outline level ${heading.level} is deeper than LaTeX's five`,
        `%% sectioning levels, so style ${heading.styleId} is not mapped.`,
      );
      continue;
    }
    lines.push(
      "",
      ...formatHeading(
        command,
        heading,
        bodySizePt,
        bodyFamily,
        usage.get(heading.styleId) ?? 0,
      ),
    );
  }

  return lines;
}

function formatHeading(
  command: string,
  heading: HeadingStyle,
  bodySizePt: number,
  bodyFamily: LatexFamily,
  uses: number,
): readonly string[] {
  const before = heading.text.allCaps ? "\\MakeUppercase" : "";
  const applied =
    uses === 0
      ? "declared but applied to no paragraph"
      : `applied to ${uses} paragraph${uses === 1 ? "" : "s"}`;

  return [
    `%% ${heading.styleId} (heading ${heading.level}) — ${applied}`,
    `\\titleformat{\\${command}}`,
    `  {${appearance(heading, bodySizePt, bodyFamily)}}`,
    "  {}{0pt}",
    `  {${before}}`,
    `\\titlespacing*{\\${command}}` +
      `{0pt}{${pt(heading.paragraph.spaceBeforePt ?? 0)}}` +
      `{${pt(heading.paragraph.spaceAfterPt ?? 0)}}`,
  ];
}

function titleCommand(
  title: NamedStyle | undefined,
  bodySizePt: number,
  bodyFamily: LatexFamily,
): readonly string[] {
  if (!title) {
    return [
      "%% The document declares no Title style.",
      "\\newcommand{\\doctotextitle}[1]{{\\centering\\LARGE\\bfseries #1\\par}}",
    ];
  }

  const body = title.text.allCaps ? "\\MakeUppercase{#1}" : "#1";

  return [
    "%% Word's Title style, which is not one of the outline levels.",
    "\\newcommand{\\doctotextitle}[1]{{" +
      appearance(title, bodySizePt, bodyFamily) +
      ` ${body}\\par}}`,
  ];
}

/** The font switches that reproduce one style, in LaTeX's declaration order. */
function appearance(
  style: EffectiveStyle,
  bodySizePt: number,
  bodyFamily: LatexFamily = "rm",
): string {
  const parts = ["\\normalfont"];

  // \normalfont resets to the document family, so a style in another face has
  // to ask for its slot back.
  const family = mapFont(style.text.fontFamily).family;
  if (style.text.fontFamily && family !== bodyFamily) {
    parts.push(`\\${family}family`);
  }

  if (style.text.bold) {
    parts.push("\\bfseries");
  }
  if (style.text.italic) {
    parts.push("\\itshape");
  }
  parts.push(fontSize(style.text.fontSizePt ?? bodySizePt));

  if (style.text.colorHex) {
    parts.push(`\\color[HTML]{${style.text.colorHex.replace("#", "")}}`);
  }
  // \centering and \raggedleft must come last: they reset the paragraph shape.
  if (style.paragraph.alignment === "center") {
    parts.push("\\centering");
  }
  if (style.paragraph.alignment === "right") {
    parts.push("\\raggedleft");
  }

  return parts.join("");
}

function pageStyle(headerFooter: HeaderFooterText): readonly string[] {
  const lines = [
    "\\RequirePackage{fancyhdr}",
    "\\pagestyle{fancy}",
    "\\fancyhf{}",
    "\\renewcommand{\\headrulewidth}{0pt}",
  ];

  // Only what the document carries. A Word file with no footer prints no page
  // number, so supplying \thepage here would add a mark the original never had.
  if (headerFooter.header) {
    lines.push(`\\fancyhead[C]{${headerFooter.header}}`);
  }
  if (headerFooter.footer) {
    lines.push(`\\fancyfoot[C]{${headerFooter.footer}}`);
  }

  return lines;
}

function separation(valueMm: number): number {
  return Math.max(MIN_SEPARATION_MM, valueMm);
}
