import { mapFont, type FontMapping, type LatexFamily } from "./fonts";
import type {
  EffectiveStyle,
  HeadingStyle,
  LineSpacing,
  NamedStyle,
  StyleProfile,
} from "@/lib/extract/types";

export const CLASS_NAME = "doctotex";

/**
 * ECMA-376 gives `w:sz` a default of 20 half-points, so a document that never
 * declares a size is asking for 10pt rather than leaving it open.
 */
const DEFAULT_BODY_SIZE_PT = 10;

/** LaTeX's own default; set explicitly so fancyhdr stops warning about it. */
const HEAD_HEIGHT_MM = 4.94;

/** geometry rejects a zero separation, and Word can legitimately ask for one. */
const MIN_SEPARATION_MM = 0.1;

/** Word outline levels, in order, to the sectioning commands they become. */
const SECTIONING = [
  "section",
  "subsection",
  "subsubsection",
  "paragraph",
  "subparagraph",
] as const;

export interface HeaderFooterText {
  readonly header?: string;
  readonly footer?: string;
}

/** How many paragraphs use each style, so unused ones can be labelled. */
export type StyleUsage = ReadonlyMap<string, number>;

export function generateClass(
  profile: StyleProfile,
  headerFooter: HeaderFooterText = {},
  usage: StyleUsage = new Map(),
): string {
  const bodySizePt = profile.defaults.text.fontSizePt ?? DEFAULT_BODY_SIZE_PT;
  const bodyFamily = mapFont(profile.defaults.text.fontFamily).family;

  return [
    ...preamble(),
    "",
    ...fontSetup(profile, bodySizePt),
    "",
    ...geometry(profile),
    "",
    ...spacing(profile),
    "",
    ...headings(profile, bodySizePt, bodyFamily, usage),
    "",
    ...titleCommand(profile.title, bodySizePt, bodyFamily),
    "",
    ...pageStyle(headerFooter),
    "",
    "\\endinput",
  ].join("\n");
}

function preamble(): readonly string[] {
  return [
    "%% Generated by DocToTex from the styles of a Word document.",
    "%% Every value below was read from the document; nothing is invented.",
    "\\NeedsTeXFormat{LaTeX2e}",
    `\\ProvidesClass{${CLASS_NAME}}[2026/08/12 DocToTex generated class]`,
    "",
    "\\LoadClassWithOptions{article}",
  ];
}

/**
 * Every distinct typeface the document uses, so a heading in Arial over a body
 * in Times still reaches the reader in Arial. Loading only the body font would
 * silently render every style in it.
 */
function fontPlan(profile: StyleProfile): ReadonlyMap<string, FontMapping> {
  const families = [
    profile.defaults.text.fontFamily,
    ...profile.headings.map((heading) => heading.text.fontFamily),
    profile.title?.text.fontFamily,
  ];

  const plan = new Map<string, FontMapping>();
  for (const family of families) {
    const key = family ?? "";
    if (!plan.has(key)) {
      plan.set(key, mapFont(family));
    }
  }
  return plan;
}

function fontSetup(
  profile: StyleProfile,
  bodySizePt: number,
): readonly string[] {
  const plan = fontPlan(profile);
  const bodyFamily = mapFont(profile.defaults.text.fontFamily).family;

  const lines = [
    "%% Fonts. T1 encoding is required for accented characters to hyphenate.",
    "\\RequirePackage[T1]{fontenc}",
  ];

  const loaded = new Set<string>();
  for (const [family, mapping] of plan) {
    if (mapping.unmatched) {
      lines.push(
        `%% TODO: the document asks for "${mapping.unmatched}", which has no free`,
        "%% counterpart for pdfLaTeX. Latin Modern is substituted. Compiling with",
        "%% XeLaTeX or LuaLaTeX would load the real face through fontspec.",
      );
    }
    for (const name of mapping.packages) {
      if (!loaded.has(name)) {
        loaded.add(name);
        lines.push(`\\RequirePackage{${name}}  % ${family || "default"}`);
      }
    }
  }

  lines.push(...collisionNotes(plan));

  if (bodyFamily !== "rm") {
    lines.push(`\\renewcommand{\\familydefault}{\\${bodyFamily}default}`);
  }

  if (profile.defaults.text.fontSizePt === undefined) {
    lines.push(
      `%% The document declares no body size, so the schema default of ${DEFAULT_BODY_SIZE_PT}pt applies.`,
    );
  }
  lines.push(
    "\\renewcommand{\\normalsize}{" + fontSize(bodySizePt) + "}",
    "\\normalsize",
  );

  return lines;
}

/**
 * Two different Word faces can map onto the same LaTeX slot — Times and
 * Garamond are both serif. pdfLaTeX cannot then tell them apart, and saying so
 * beats letting one quietly become the other.
 */
function collisionNotes(
  plan: ReadonlyMap<string, FontMapping>,
): readonly string[] {
  const bySlot = new Map<LatexFamily, string[]>();
  for (const [family, mapping] of plan) {
    if (family !== "") {
      bySlot.set(mapping.family, [
        ...(bySlot.get(mapping.family) ?? []),
        family,
      ]);
    }
  }

  return [...bySlot]
    .filter(([, families]) => families.length > 1)
    .map(
      ([slot, families]) =>
        `%% TODO: ${families.join(" and ")} both map to \\${slot}family, so pdfLaTeX renders them alike.`,
    );
}

function geometry(profile: StyleProfile): readonly string[] {
  const { widthMm, heightMm, margins } = profile.page;

  // Word measures the header from the page edge; geometry measures it from the
  // text block. The conversion is the top margin less the header offset and the
  // height of the header itself.
  const headSep = separation(margins.topMm - margins.headerMm - HEAD_HEIGHT_MM);
  const footSkip = separation(margins.bottomMm - margins.footerMm);

  return [
    "%% Page geometry, taken from the document's section properties.",
    "\\RequirePackage{geometry}",
    "\\geometry{",
    `  paperwidth=${mm(widthMm)},`,
    `  paperheight=${mm(heightMm)},`,
    `  top=${mm(margins.topMm)},`,
    `  bottom=${mm(margins.bottomMm)},`,
    `  left=${mm(margins.leftMm)},`,
    `  right=${mm(margins.rightMm)},`,
    `  headheight=${mm(HEAD_HEIGHT_MM)},`,
    `  headsep=${mm(headSep)},`,
    `  footskip=${mm(footSkip)}`,
    "}",
  ];
}

function spacing(profile: StyleProfile): readonly string[] {
  const lines = ["\\RequirePackage{setspace}", "\\RequirePackage{xcolor}"];

  const stretch = stretchFor(profile.defaults.paragraph.lineSpacing);
  if (stretch !== undefined) {
    lines.push(`\\setstretch{${stretch}}`);
  }

  const { spaceBeforePt, spaceAfterPt, indentFirstLineMm } =
    profile.defaults.paragraph;

  // Both are set unconditionally. Word's defaults for an undeclared indent and
  // an undeclared paragraph spacing are zero, while LaTeX's are a 15pt indent
  // and a springy parskip — leaving them alone would indent every paragraph of
  // a document that asked for none.
  lines.push(
    `\\setlength{\\parskip}{${pt(spaceAfterPt ?? spaceBeforePt ?? 0)}}`,
    `\\setlength{\\parindent}{${mm(indentFirstLineMm ?? 0)}}`,
  );

  return lines;
}

function headings(
  profile: StyleProfile,
  bodySizePt: number,
  bodyFamily: LatexFamily,
  usage: StyleUsage,
): readonly string[] {
  const lines = [
    "%% Heading styles, one per outline level the document declares.",
    "\\RequirePackage{titlesec}",
  ];

  if (profile.headings.length === 0) {
    lines.push("%% The document declares no heading styles.");
    return lines;
  }

  const used = profile.headings.filter((h) => (usage.get(h.styleId) ?? 0) > 0);
  if (used.length === 0) {
    lines.push(
      "%% None of these styles is applied to any paragraph in the document:",
      "%% every heading in it is a normal paragraph formatted by hand. The",
      "%% definitions are kept so the structure can be applied by hand here.",
    );
  }

  for (const heading of profile.headings) {
    const command = SECTIONING[heading.level - 1];
    if (!command) {
      lines.push(
        `%% TODO: outline level ${heading.level} is deeper than LaTeX's five`,
        `%% sectioning levels, so style ${heading.styleId} is not mapped.`,
      );
      continue;
    }
    lines.push(
      "",
      ...formatHeading(
        command,
        heading,
        bodySizePt,
        bodyFamily,
        usage.get(heading.styleId) ?? 0,
      ),
    );
  }

  return lines;
}

function formatHeading(
  command: string,
  heading: HeadingStyle,
  bodySizePt: number,
  bodyFamily: LatexFamily,
  uses: number,
): readonly string[] {
  const before = heading.text.allCaps ? "\\MakeUppercase" : "";
  const applied =
    uses === 0
      ? "declared but applied to no paragraph"
      : `applied to ${uses} paragraph${uses === 1 ? "" : "s"}`;

  return [
    `%% ${heading.styleId} (heading ${heading.level}) — ${applied}`,
    `\\titleformat{\\${command}}`,
    `  {${appearance(heading, bodySizePt, bodyFamily)}}`,
    "  {}{0pt}",
    `  {${before}}`,
    `\\titlespacing*{\\${command}}` +
      `{0pt}{${pt(heading.paragraph.spaceBeforePt ?? 0)}}` +
      `{${pt(heading.paragraph.spaceAfterPt ?? 0)}}`,
  ];
}

function titleCommand(
  title: NamedStyle | undefined,
  bodySizePt: number,
  bodyFamily: LatexFamily,
): readonly string[] {
  if (!title) {
    return [
      "%% The document declares no Title style.",
      "\\newcommand{\\doctotextitle}[1]{{\\centering\\LARGE\\bfseries #1\\par}}",
    ];
  }

  const body = title.text.allCaps ? "\\MakeUppercase{#1}" : "#1";

  return [
    "%% Word's Title style, which is not one of the outline levels.",
    "\\newcommand{\\doctotextitle}[1]{{" +
      appearance(title, bodySizePt, bodyFamily) +
      ` ${body}\\par}}`,
  ];
}

/** The font switches that reproduce one style, in LaTeX's declaration order. */
function appearance(
  style: EffectiveStyle,
  bodySizePt: number,
  bodyFamily: LatexFamily = "rm",
): string {
  const parts = ["\\normalfont"];

  // \normalfont resets to the document family, so a style in another face has
  // to ask for its slot back.
  const family = mapFont(style.text.fontFamily).family;
  if (style.text.fontFamily && family !== bodyFamily) {
    parts.push(`\\${family}family`);
  }

  if (style.text.bold) {
    parts.push("\\bfseries");
  }
  if (style.text.italic) {
    parts.push("\\itshape");
  }
  parts.push(fontSize(style.text.fontSizePt ?? bodySizePt));

  if (style.text.colorHex) {
    parts.push(`\\color[HTML]{${style.text.colorHex.replace("#", "")}}`);
  }
  // \centering and \raggedleft must come last: they reset the paragraph shape.
  if (style.paragraph.alignment === "center") {
    parts.push("\\centering");
  }
  if (style.paragraph.alignment === "right") {
    parts.push("\\raggedleft");
  }

  return parts.join("");
}

function pageStyle(headerFooter: HeaderFooterText): readonly string[] {
  const lines = [
    "\\RequirePackage{fancyhdr}",
    "\\pagestyle{fancy}",
    "\\fancyhf{}",
    "\\renewcommand{\\headrulewidth}{0pt}",
  ];

  if (headerFooter.header) {
    lines.push(`\\fancyhead[C]{${headerFooter.header}}`);
  }
  lines.push(
    headerFooter.footer
      ? `\\fancyfoot[C]{${headerFooter.footer}}`
      : "\\fancyfoot[C]{\\thepage}",
  );

  return lines;
}

/** Word's line rule maps onto setspace's stretch factor only when it is auto. */
function stretchFor(spacing: LineSpacing | undefined): number | undefined {
  if (spacing?.kind !== "multiple") {
    return undefined;
  }
  return spacing.value;
}

function fontSize(sizePt: number): string {
  // 1.2 is TeX's own ratio of baseline to size.
  return `\\fontsize{${trim(sizePt)}pt}{${trim(sizePt * 1.2)}pt}\\selectfont`;
}

function separation(valueMm: number): number {
  return Math.max(MIN_SEPARATION_MM, valueMm);
}

function mm(value: number): string {
  return `${trim(value)}mm`;
}

function pt(value: number): string {
  return `${trim(value)}pt`;
}

function trim(value: number): string {
  return String(Math.round(value * 100) / 100);
}
